Pages/ContactUs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using System.Net;
using HamzilahFoods.Data;

namespace HamzilahFoods.Pages
{
    public class ContactUsModel : PageModel
    {
        public string Message { get; set; }

        private IConfiguration Configuration;
        public ContactUsModel(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        public void OnGet()
        {
        }
        public void OnPostSubmit(ContactFormModel model)
        {
            //Read SMTP settings from AppSettings.json.
            string host = this.Configuration.GetValue<string>("Smtp:Server");
            int port = this.Configuration.GetValue<int>("Smtp:Port");
            string fromAddress = this.Configuration.GetValue<string>("Smtp:FromAddress");
            string userName = this.Configuration.GetValue<string>("Smtp:UserName");
            string password = this.Configuration.GetValue<string>("Smtp:Password");

            using (MailMessage mm = new MailMessage(fromAddress, "admin@aspsnippets.com"))
            {
                mm.Subject = model.Subject;
                mm.Body = "Name: " + model.Name + "<br /><br />Email: " + model.Email + "<br />" + model.Body;
                mm.IsBodyHtml = true;

                if (model.Attachment.Length > 0)
                {
                    string fileName = Path.GetFileName(model.Attachment.FileName);
                    mm.Attachments.Add(new Attachment(model.Attachment.OpenReadStream(), fileName));
                }

                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = host;
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(userName, password);
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = port;
                    smtp.Send(mm);
                    this.Message = "Email sent sucessfully.";
                }
            }
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace HamzilahFoods.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HamzilahFoods.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Menu.cshtml.cs
using HamzilahFoods.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace HamzilahFoods.Pages
{
    public class MenuModel : PageModel
    {
        private readonly HamzilahFoods.Data.HamzilahFoodsContext _context;

        public MenuModel(HamzilahFoods.Data.HamzilahFoodsContext context)
        {
            _context = context;
        }

        public IList<Menu> Menu { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Menu != null)
            {
                Menu = await _context.Menu.ToListAsync();
            }
        }
    }
}

Pages/UploadImage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HamzilahFoods.Pages
{
    public class UploadImageModel : PageModel
    {
        private readonly ILogger<UploadImageModel> _logger;
        private readonly IHostEnvironment _environment;

        [BindProperty]

        public IFormFile UploadedFile { get; set; }

        public UploadImageModel(ILogger<UploadImageModel> logger, IHostEnvironment environment)
        {
            _logger = logger;
            _environment = environment;
        }
        public void OnGet()
        {
        }
        public async Task OnPostAsync()
        {
            if (UploadedFile == null || UploadedFile.Length == 0)
            {
                return;
            }
            _logger.LogInformation($"Uploading {UploadedFile.FileName}.");
            var id = Request.Query["id"];
            string extension = Path.GetExtension(UploadedFile.FileName);
            string newfilename = id + extension;
            string targetFileName = $"{_environment.ContentRootPath}/wwwroot/img/{newfilename}";

            using (var stream = new FileStream(targetFileName, FileMode.Create))
            {
                await UploadedFile.CopyToAsync(stream);
            }
        }
    }
}

Pages/ContactUs.cshtml
@page
@model HamzilahFoods.Pages.ContactUsModel
@{
}
<link rel="stylesheet" href="~/css/Contact.css" />

<br>

    <h4>  Contact Us</h4>
    <div class="container">
    <div class="Leftside">
    <form method="post" enctype="multipart/form-data">
        <table border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td style="width: 80px">Name:</td>
                <td><input type="text" name="Name" /></td>
            </tr>
            <tr>
                <td>Subject:</td>
                <td><input type="text" name="Subject" /></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><input type="text" name="Email" /></td>
            </tr>
            <tr>
                <td valign="top">Body:</td>
                <td><textarea cols="20" rows="10" name="Body"></textarea></td>
            </tr>
            <tr>
                <td>Attachment:</td>
                <td><input type="file" name="Attachment" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Send" asp-page-handler="Submit" /></td>
            </tr>
        </table>
        <br />
        <span style="color:green">@Model.Message</span>
    </form>
    </div>

<div class="rightside">
<div class="map" postion="inherit">
        <iframe src="https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d3966.982321242796!2d114.81904899269291!3d4.841179585883513!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNMKwNTAnMjguMiJOIDExNMKwNDknMTcuOSJF!5e0!3m2!1sen!2sbn!4v1685544573859!5m2!1sen!2sbn" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.0.20/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({ selector: 'textarea', width: 300 });
    </script>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Homepage";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@using HamzilahFoods.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

    @if (SignInManager.IsSignedIn(User))
    {
        <h4>hello, @UserManager.GetUserName(User)</h4>
    }


    

<div class="container">
    <div>
        <h1 class="heading"> LOCAL BRUNEIAN TASTE</h1>
        <p class="greeting"> Welcome to Hamzilah Foods official website</p>
        <p class=" paragraph"> Here we serve authentic malay dishes that you'll never forget</p>
    </div>
   
  
</div>

Pages/Menu.cshtml
@page
@model MenuModel
@{
    ViewData["Title"] = "Privacy Policy";
}
<link rel="stylesheet" href="~/css/Menu.css" />

<h1>Menu</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Menu[0].ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Menu[0].ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Menu[0].ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Menu[0].Price)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Menu) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
                    @{
                        var imagepath = @"img\" + item.ID + ".png";
                    }
                <td>
                    <img src="@imagepath">
                </td>
        </tr>
}
    </tbody>
</table>

Pages/UploadImage.cshtml
@page
@model HamzilahFoods.Pages.UploadImageModel
@{
    ViewData["Title"] = "Upload Image";
}
<div class="text-center">
    <h1>Upload Image</h1>
</div>

<form method="post" enctype="multipart/form-data">
    <input asp-for="UploadedFile" />
    <input type="submit" />
</form>